### ISSUE TITLE
figure out how to remotely connect to the mongodb in python (week 9)

### ISSUE THREAD

**Issue by ArktinenSieni** [datascienceproject2019-codescoop/codescoop-models#4]

**Comment by ArktinenSieni** [comment]
Could you elaborate @andrei-comanescu ? Do you need this feature to our backend tool or the models? I probably can help with that.

**Comment by andrei-comanescu** [comment]
Just writing the script to query the data from ghtorrent, until now I just made queries in a terminal. We need the data for the models.
